-- Run this entire block in the Supabase SQL Editor

-- 1. Create the employees table
CREATE TABLE public.employees (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    role text not null,
    phone text,
    email text
);

-- 2. Create the clients table
CREATE TABLE public.clients (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    person_type text default 'adult',
    parent_id bigint references public.clients(id) on delete cascade,
    date_of_birth date,
    gender text,
    phone text,
    email text,
    sms_consent text default 'neutral',
    email_consent text default 'neutral',
    interests text,
    total_sales numeric default 0
);

-- 3. Create the vendors table
CREATE TABLE public.vendors (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    category text not null,
    phone text,
    email text
);

-- 4. Create the events table
CREATE TABLE public.events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    date timestamp with time zone not null,
    type text not null,
    client_id bigint references public.clients(id) on delete cascade,
    user_auth_id uuid references auth.users(id) on delete set null
);

-- Enable Row Level Security (RLS) but set policies to allow all authenticated users
-- for MVP internal tool purposes.
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read/insert/update/delete
CREATE POLICY "Allow authenticated full access employees" ON public.employees FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access clients" ON public.clients FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access vendors" ON public.vendors FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access events" ON public.events FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 5. Allow public to insert clients for the waitlist form
CREATE POLICY "Allow public to insert clients" ON public.clients FOR INSERT TO anon WITH CHECK (true);

-- 6. Create the webforms table (form definitions)
CREATE TABLE public.webforms (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    slug text not null unique,
    description text,
    fields jsonb not null default '[]'::jsonb,
    is_active boolean default true
);

-- 7. Create the form_submissions table
CREATE TABLE public.form_submissions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    form_id bigint references public.webforms(id) on delete cascade not null,
    data jsonb not null default '{}'::jsonb,
    matched_client_id bigint references public.clients(id) on delete set null
);

-- Enable RLS
ALTER TABLE public.webforms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_submissions ENABLE ROW LEVEL SECURITY;

-- Authenticated users get full access
CREATE POLICY "Allow authenticated full access webforms" ON public.webforms FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access form_submissions" ON public.form_submissions FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Anon can read webforms (to load public form) and insert submissions
CREATE POLICY "Allow anon to read webforms" ON public.webforms FOR SELECT TO anon USING (is_active = true);
CREATE POLICY "Allow anon to insert form_submissions" ON public.form_submissions FOR INSERT TO anon WITH CHECK (true);
