-- Run this entire block in the Supabase SQL Editor

-- 1. Create the employees table
CREATE TABLE public.employees (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    role text not null,
    phone text,
    email text
);

-- 2. Create the clients table
CREATE TABLE public.clients (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    type text not null,
    phone text,
    email text,
    total_sales numeric default 0
);

-- 3. Create the vendors table
CREATE TABLE public.vendors (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    category text not null,
    phone text,
    email text
);

-- 4. Create the events table
CREATE TABLE public.events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    date timestamp with time zone not null,
    type text not null,
    client_id bigint references public.clients(id) on delete cascade,
    user_auth_id uuid references auth.users(id) on delete set null
);

-- Enable Row Level Security (RLS) but set policies to allow all authenticated users
-- for MVP internal tool purposes.
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read/insert/update/delete
CREATE POLICY "Allow authenticated full access employees" ON public.employees FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access clients" ON public.clients FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access vendors" ON public.vendors FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated full access events" ON public.events FOR ALL TO authenticated USING (true) WITH CHECK (true);
